### ISSUE TITLE
users-admin routes and views not included?

### ISSUE THREAD

**Issue by mg1075** [StetSolutions/pean#10]
Looking at the users-admin routes, it looks like the admin portion is commented out.
https://github.com/StetSolutions/pean/blob/master/modules/users/client/config/users-admin.client.routes.js

A few user admin views are also not included.

Do you know the reason these admin-related files are not included?

**Comment by francisdaigle** [comment]
Ah. Poor housecleaning :)

Those routes should have been removed. I changed the User admin to that of a "single view". As such, the application no longer requires those particular routes.
