### ISSUE TITLE
abstract the sequelize host and port?

### ISSUE THREAD

**Issue by mg1075** [StetSolutions/pean#17]
Do you believe it would be good to abstract the sequelize host and port?

Actually, it might be good to abstract the dialect too, 
because then you could plug in SQLite, etc., in a 
more configurable way. Have not checked to see what all 
pieces might be impacted, though.

https://github.com/StetSolutions/pean/blob/master/config/lib/sequelize.js#L12-L17

```
var sequelize = new Sequelize(config.db.options.database, config.db.options.username, config.db.options.password, {
  dialect: 'postgres',
  logging: false, // console.log
  host: 'localhost',
  port: '5432'
});
```

**Comment by francisdaigle** [comment]
Hmmm... well, changing the dialect would be no good as you would be no longer able to take advantage of PG's NoSQL abilities. Further to that, the User module utilizes these NoSQL features so the module would have to be revamped. 

As far as the the host and port are concerned, yes, I agree - they should be abstracted out. Good call.
