### ISSUE TITLE
reset-password.js?

### ISSUE THREAD

**Issue by mg1075** [StetSolutions/pean#2]
The mean 0.4.2 branch has a file under the scripts folder called reset-password.js.
https://github.com/meanjs/mean/blob/v0.4.2/scripts/reset-password.js

Is file absent by design? It does have mongoose dependency in mean.

**Comment by francisdaigle** [comment]
I removed it as I was short on time and did not want to go to the effort of rewriting the script. I was hoping someone might make a PR at some point. It's somewhat "non-essential" however so not a huge priority. Would be nice to have though :)
