### ISSUE TITLE
login: incorrect password

### ISSUE THREAD

**Issue by mg1075** [StetSolutions/pean#24]
Trying to login with the wrong password leads to this error message in the terminal.

> Warning: a promise was created in a handler but was not returned from it

modules\users\server\controllers\users\users.authentication.server.controller.js:108:23

https://github.com/StetSolutions/pean/blob/master/modules/users/server/controllers/users/users.authentication.server.controller.js#L108

**Comment by francisdaigle** [comment]
Ah. Good catch:)

Recent versions of Bluebird (the promise library used by Sequelize) output this warning whenever a promise is created but not returned (a "hanging" promise). Although "just a warning", the warning can be silenced by returning "null".

Further Information can be found here:
http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

**Comment by mg1075** [comment]
Hmm... if returning "null" after the res.status... on line 108, the error still occurs; if solely returning null, and no res.status..., then the login page does not show the "invalid..." message; but if using 

```
res.status(400).send(info);
return res.status(400).send(info);
```

....then no error, and the "Invalid username or password" message appears in the UI as it should.

**Comment by francisdaigle** [comment]
HI @mg1075 :)

My apologies for the late response. I wonder if this might be an [issue](https://www.google.ca/search?q=%22Warning%3A+a+promise+was+created+in+a+handler+but+was+not+returned+from+it+at+ConnectionManager.getConnection%22&oq=%22Warning%3A+a+promise+was+created+in+a+handler+but+was+not+returned+from+it+at+ConnectionManager.getConnection%22&aqs=chrome..69i57.4544j0j4&sourceid=chrome&ie=UTF-8) with the Sequelize connection manager? I'm at a loss :/

**Comment by francisdaigle** [comment]
@mg1075: #25 appears to silence the warning. 

The "local strategy" failed to return the promise created by Sequelize when "finding" the user (as the "failed" user is nonexistent). 

The fix is to return "null" of course. So, instead of returning Passport's "done()" callback, we return "null" instead.
