### ISSUE TITLE
Use with Mobile API

### ISSUE THREAD

**Issue by Usman-Asghar** [StetSolutions/pean#26]
Hello,

I want to use your PEAN Stack for my Mobile as a REST Full API, So can you please guide me how i can call different URL's from my Mobile end. I try to call but i get this error at Mobile end "User is not authorized". Please let me know as soon as possible.

**Comment by francisdaigle** [comment]
Hmmm... you're wanting to use PEAN as an API, correct? You'll want to look at your routes, strategies and associated policies. 

PEAN uses [Passport.js](http://passportjs.org/docs/overview) for authentication. By default, PEAN employs Passport's ["local"](http://passportjs.org/docs/username-password) strategy (traditional "username/password" authentication). 

Receiving a "401" would indicate that the "user" has not logged in. As such, routes that require an authorized user will return the message "User is not authorized".

So, you'll have to make sure your mobile users "log in" (if you're using the basic/traditional default local strategy) or use some other means of authentication (such as [OAuth](http://passportjs.org/docs/oauth) for "one-time" authentication).
