### ISSUE TITLE
consider changing admin search query operators

### ISSUE THREAD

**Issue by mg1075** [StetSolutions/pean#27]
https://github.com/StetSolutions/pean/blob/master/modules/users/server/controllers/users/users.admin.server.controller.js#L91

The `.list` function which the user admin page uses to display a list of users has the ability to filter users by the input box value above the users table.

It might be better to use `$iLike` instead of `$like` when filtering in the server `.list` function, since case-sensitive search seems too limiting.

**Comment by francisdaigle** [comment]
Hmmm... well, I think it might be best to leave this to the users discretion as I would think that "generally" the user would expect the query to be case sensitive (especially being that `$iLike` is PG specific). 

My "rule of thumb" with things of this nature is to start with a "general" solution and move towards something more "specific" as the need arises. So, in this instance, I think the general "expectation" would be case sensitivity. 

Maybe a config option would be more appropriate (with the default being case insensitive). That way the user has a choice.
