### ISSUE TITLE
error in variable configuration for express.js

### ISSUE THREAD

**Issue by mg1075** [StetSolutions/pean#28]
Please see:
https://github.com/StetSolutions/pean/blob/7f0db97c18769745828bd176aac76af25b93e262/config/lib/express.js#L123

![image](https://cloud.githubusercontent.com/assets/2031435/18897804/c2ddd732-84f2-11e6-8035-e112a059cf09.png)

I do not know where "config.sessionExpiration" is supposed to be coming from, because I see no where where it is set. Moreover, as far as I can tell, session expiration is not working. Try changing config/env/default.js **maxAge** to 5 seconds, and sessions still do not expire.

I'm pretty sure in **express.js** that you want to set the maxAge as:
`maxAge: config.sessionCookie.maxAge`

**Comment by mg1075** [comment]
Once the `maxAge` variable was set, 
there was another issue that crept up:
the session expired as the `maxAge`, regardless of user activity.

As per a hint in this stackoverflow answer, 
- http://stackoverflow.com/a/24794410/538962

when adding `rolling: true` to config/lib/express, 
then the session did not expire while the user maintained
activity in the app.

![image](https://cloud.githubusercontent.com/assets/2031435/18940299/80786292-85cc-11e6-84ac-e05d470297e7.png)

**Comment by francisdaigle** [comment]
Good catch! Looks like an oversight. 

Would you be willing to submit a PR?

**Comment by mg1075** [comment]
...kind of swamped today;
f.y.i. - here is a discussion on the mean.js gitter
- https://gitter.im/meanjs/mean

[image: Inline image 1]

[image: Inline image 2]

**Comment by francisdaigle** [comment]
No worries :)

Well, I think the simplest thing to do would be to change `config.maxAge` to `config.sessionCookie.maxAge`. Personally, I'm fine with the Express default (providing this oversight is fixed of course). 

I'll try and take care of this later today. Wouldn't want anyone tripping on this. 

Thanks again for the catch!
