### ISSUE TITLE
localhost connection denied

### ISSUE THREAD

**Issue by AirJordan6811** [StetSolutions/pean#29]
Hello,
grunt started. Error:

> Unhandled rejection SequelizeConnectionError: password authentication failed for user "user"

> http://localhost:3000/
firefox returns "Connection Rejected"

I have changed the local-development.js, local-test.js, local-production.js and added NODE_ENV.js
and I have installed and set the pean Full-Stack JavaScript as described. What am I doing wrong?

Greetings from Hamburg
Holger

**Comment by mg1075** [comment]
Is the db seeded, and there are users in the Users table?

**Comment by AirJordan6811** [comment]
Yes db seeded:

> init: process.env.DB_SEED === 'true' ? true : false,
>     logging: process.env.DB_SEED_LOGGING === 'false' ? false : true

user also in my database

**Comment by AirJordan6811** [comment]
> Unhandled rejection SequelizeConnectionError: password authentication failed for user "holger"

and the user "holger" has a role with all rights.

**Comment by francisdaigle** [comment]
Were you able to resolve your issue Holger? I'm fairly certain this is a "permissions" issue and not an issue with PEAN itself.

**Comment by AirJordan6811** [comment]
no, I have the problem not solved. Where I need to make the settings, so I can set the user 'holger' correctly? 

## local-NODE-ENV.js

> module.exports = {
>   db: {
>     options: {
>       database: 'bvshweb',
>       password: '*********',
>       username: 'holger'
>     }
>   },
>   sessionSecret: process.env.SESSION_SECRET || 'youshouldchangethistosomethingsecret',
>   facebook: {
>     clientID: process.env.FACEBOOK_ID || 'APP_ID',
>     clientSecret: process.env.FACEBOOK_SECRET || 'APP_SECRET',
>     callbackURL: '/api/auth/facebook/callback'
>   }
> };

**Comment by AirJordan6811** [comment]
> Unhandled rejection SequelizeConnectionError: password authentication failed for user "holger"

Why is the user "holger" required by "Sequelize"? If I change the settings in "local-NODE-ENV" to "postgres user" and my database, the user "holger" is required again from "Sequelize". Why?

**Comment by francisdaigle** [comment]
Sequelize is the ORM used by the application. Sequelize requires access to your DB. According to the error message, Sequelize cannot "connect" to your DB using the credentials provided. 

I would first try logging into your DB via the command line:

`psql -d mydb -U myuser`

**Comment by AirJordan6811** [comment]
Thx Francis for your fast answers. I will check the login command for sequelize. But where can I set the user and passwort for sequelize deposit fixed?

**Comment by AirJordan6811** [comment]
I can not get any further. I can go via Firefox phppgadmin over localhost: 3000 and login as user holger.
The localhost: 3000 call returns as an error "not found The requested URL / was not found on this server".

The crucial question remains why the user "holger" remains unknown to Sequelize.

> Unhandled rejection SequelizeConnectionError: password authentication failed for user "holger"
