### ISSUE TITLE
Use only NPM+Browserify(or something else like Webpack) for manage packages and remove Bower ?

### ISSUE THREAD

**Issue by billyjov** [StetSolutions/pean#32]
Bower doesn’t support nested dependencies. If the packages we use contain subdependencies, Bower resolves them into a flat dependency list, which must satisfy all subdependency requirements. If Bower cannot find a version of the dependency that meets all the conditions, then you get a conflict and must resolve it by hand *e.g  on linux*.

**Comment by francisdaigle** [comment]
This is true. PEAN is an adaptation of [MEAN](https://github.com/meanjs/mean). PEAN was created to illustrate how one might go about migrating from MongoDB to PostgreSQL (>9.4). As such, we wanted it to deviate as little as possible from the parent project.

**Comment by billyjov** [comment]
Maybe do this here and then make a PR in the mean repository ?
