### ISSUE TITLE
User forbidden after grunt reload

### ISSUE THREAD

**Issue by dawidjk** [StetSolutions/pean#33]
After I create a user with the application, everything is fine and I can log in and view all of the menus (change password, change profile picture, etc). However, once I make a change to the code, the user is forbidden from entering the page. I have to create a new user in order to view the menus again.

![image](https://user-images.githubusercontent.com/11511901/29628693-412538aa-8804-11e7-80db-5adb0d5a5c73.png)

**Comment by francisdaigle** [comment]
@dave07747: Were you able to resolve your issue?

**Comment by dawidjk** [comment]
I ended up switching to mysql and I don't have the issue anymore, maybe something to do with postgres? Although in all honesty I would prefer postgres

**Comment by francisdaigle** [comment]
Hmmm... we've not had any issues ourselves. Possibly a PG config issue?

**Comment by dawidjk** [comment]
Might very well be. I'll play around with it in a bit when I have more
time. Thanks for the responses though!
