### ISSUE TITLE
development.js: should sync be false?

### ISSUE THREAD

**Issue by mg1075** [StetSolutions/pean#4]
Because the sync property is set to true in the development environment, 
the Users table gets dropped, so if you added any users via the web "Sign Up" feature, 
they're gone when you re-start.
https://github.com/StetSolutions/pean/blob/master/config/env/development.js#L12

Should the sync property be set to false, or was there a reason to set it to true
that I'm missing?

http://docs.sequelizejs.com/en/latest/api/sequelize/?highlight=sync

**Comment by francisdaigle** [comment]
Hmmm... The only reason I can think to keep "sync" (which might be better called "force" now that I think about it) set "true" is that the user might not initially be aware that such an option exists. 

https://github.com/StetSolutions/pean/blob/master/config/lib/app.js#L17   

"sync" (force) needs to be set "true" if wanting Sequelize to add tables to PG "automagically". 

I guess my initial reasoning was that, set "true", things "just work". I'm fine either way. What do you think?

**Comment by mg1075** [comment]
@francisdaigle After investigation, won't calling `sync` itself create the tables "automagically" if they are not there? 

If the tables _are _already there, and you use `force: true`, then the a `DROP TABLE IF EXISTS` will be part of the sync process, meaning the existing model tables get wiped out/re-made.

http://stackoverflow.com/a/21075579/538962
http://sequelize.readthedocs.org/en/latest/api/sequelize/#sync

**Comment by francisdaigle** [comment]
That's right @mg1075 . I guess the question is: Is this behaviour necessary? My initial reasoning was that, ideally, the first time user should have to do nothing more than type "npm install" followed by "grunt". That way, they know that it "works". If they then want to know why their data is being lost every subsequent restart, they can look for the option. 

The thing is, it appears that the tables are being created regardless of whether credentials are set or "sync=true". The tables appear to be generated in the default user database. Strange behaviour. I don't think this is necessarily a good thing though. Hmmmm...
