### ISSUE TITLE
add unique constraint on server model for role?

### ISSUE THREAD

**Issue by mg1075** [StetSolutions/pean#6]
For the role, should you add a "unique: true" constraint?

https://github.com/StetSolutions/pean/blob/master/modules/users/server/models/role.server.model.js#L6

As is, the same role text can be added multiple times. 
Indeed, that is what was happening after I restarted the application: 
the roles table kept filling up with the same role names with incremented id's.
(I think I was using "force: false" in development.js when this happened.)

**Comment by francisdaigle** [comment]
Good catch. I agree. 

We should probably account for duplicates in the initial "seeding" as well. 

https://github.com/StetSolutions/pean/blob/master/config/lib/app.js#L23
https://github.com/StetSolutions/pean/blob/master/config/lib/seed.js#L166

Hmmm... I think this might be another one of those "just works" situations. The seeded roles are needed for permissions. However, we have Roles being "reseeded" upon every refresh. Might there be a better solution?
