### ISSUE TITLE
use underscored columns rather than camelcase?

### ISSUE THREAD

**Issue by mg1075** [StetSolutions/pean#7]
When using PostgreSQL editors like pgadmin iii to write and/or edit queries, it can be a pain if the db does not use lowercase characters.

Note the double-quotes around the Table Name, the createdAt, updatedAt, and the constraints.

```
CREATE TABLE "Roles"
(
  id serial NOT NULL,
  role character varying(255),
  "createdAt" timestamp with time zone NOT NULL,
  "updatedAt" timestamp with time zone NOT NULL,
  CONSTRAINT "Roles_pkey" PRIMARY KEY (id),
  CONSTRAINT "Roles_role_key" UNIQUE (role)
)
...
```

Sequelize offers a way to define a model or the entire db so that underscores are used, thereby avoiding the double-quotes issue. 

http://stackoverflow.com/questions/29828676/change-default-column-name-sequelize

Any opinion on forcing columns to be underscored?

**Comment by francisdaigle** [comment]
Sounds good to me :) 

Are there any drawbacks to this approach that you know of?

**Comment by mg1075** [comment]
Possibly. I have to get more familiar with Sequelize, and in the meantime I wonder what happens in this scenario: 

Would the foreign key reference to **userId** here have to refer to the actual column name in the db (potentially **user_id**) or its representation in the Sequelize model for a User?

```
  var Article = sequelize.define('Article', {
    title: {
      type: DataTypes.STRING,
      allowNull: false,
      defaultValue: null
    },
    content: DataTypes.TEXT
  }, {
    classMethods: {
      associate: function(models) {
        Article.belongsTo(models.User, {
          foreignKey: 'userId',
          foreignKeyConstraint: true
        });
      }
    }
  });
```

**Comment by francisdaigle** [comment]
Hmmm... According to the docs, "foreignKey" would refer to the actual column name:

http://docs.sequelizejs.com/en/latest/docs/associations/

**Comment by francisdaigle** [comment]
Hmmm... looking at this again. In PSQL, unquoted identifiers automatically fold to lowercase - hence the need for quotes on camelCase identifiers. 

I kinda prefer snake_case/underscores myself but I think most JS applications go with camelCase as, idiomatically, it makes more sense not having to switch between contexts. As well, it would be a PITA to revamp the whole of the application for the sake of preference.

My vote is to stay with the default camelCase and leave the rest to user preference. 

Thoughts?

**Comment by francisdaigle** [comment]
Closing as this seems to be a "non-issue". 

Please feel free to "reopen" if you would like to discuss the topic further.
