### ISSUE TITLE
update sequelize to newer version?

### ISSUE THREAD

**Issue by mg1075** [StetSolutions/pean#9]
When running npm install, there was a notice about sequelize.
The project uses 3.13, whereas sequelize is on 3.18 at this time.
https://github.com/sequelize/sequelize/blob/master/changelog.md

The warning about 3.13 during the npm install was a fix addressed in 3.17.
The changelog for 3.17.0 says "Fixed injection vulnerability for order/limit".

**Comment by francisdaigle** [comment]
Ah. Yes. There was an updated version of the Bluebird (http://bluebirdjs.com/docs/getting-started.html) promise library that the Sequelize team had yet to account for so I temporarily set Sequeize to a static version that "worked". I'll check and see if the issue has been resolved :)
